### ISSUE TITLE
Error that breaks JMod and GChem

### ISSUE THREAD

**Issue by KekkyShmekky** [Zero2003/ulx-custom-commands#4]
```
[ulx-custom-commands] addons/ulx-custom-commands/lua/ulx/modules/sh/cc_hook.lua:8: attempt to call method 'IsSuperAdmin' (a nil value)
  1. call - addons/ulx-custom-commands/lua/ulx/modules/sh/cc_hook.lua:8
   2. __fn - lua/ulib/shared/commands.lua:951
    3. execute - lua/ulib/shared/commands.lua:1331
     4. execStringULib - lua/ulib/shared/util.lua:339
      5. fn - lua/ulx/end.lua:4
       6. fn - lua/ulx/end.lua:131
        7. unknown - lua/ulib/shared/hook.lua:109
```
        
 So this happens whenever I want to switch from the other ULX Custom Commands addon because it apparently has a broken string during launch. With this addon installed, however, I feel like this error may be the cause of a lot of network-related errors with the addons JMod, GChem, plus some custom networking done on my end. I've tried using the IsUserGroup alternative but for some reason it also returns as a nil value.
 
To elaborate, it spams those errors throughout console non-stop until I replace this addon with the other commands addon.

**Comment by thebigyap** [comment]
Do you have the base ulx modules installed? They are what defines the function IsSuperAdmin. It's erroring out because it can't find that function (nil).

**Comment by KekkyShmekky** [comment]
Yes, I do have the base ULX modules installed

**Comment by thebigyap** [comment]
Just to check all bases,
you have ulx, ulib, and ulx_cc installed on your server?
I haven't seen this issue on hosts that have all of these, but I am unfamiliar with those gamemodes. Maybe there is something inside of them that is breaking it or maybe it has to do with your current addons.
If the answer to the above is yes, what addons do you currently have installed on the server and are you currently using JMod or GChem?
