### ISSUE TITLE
csaycolor not properly working for other clients

### ISSUE THREAD

**Issue by Quesoteric** [Zero2003/ulx-custom-commands#5]
What it says on the tin, csaycolor will fail to broadcast to _other_ players. If you're executing the command not from the server console, it will still display fine on your end and your end only. Executing it in the srcds console, however, spits out this error;
```
[ulx-custom-commands-master] addons/ulx-custom-commands-master/lua/ulx/modules/sh/cc_chat.lua:80: bad argument #1 to ULib.clientRPC (nil,Player,table expected, got Entity)
  1. error - [C]:-1
   2. checkArg - addons/ulib/lua/ulib/shared/misc.lua:585
    3. clientRPC - addons/ulib/lua/ulib/server/util.lua:26
     4. csay - addons/ulib/lua/ulib/shared/messages.lua:221
      5. call - addons/ulx-custom-commands-master/lua/ulx/modules/sh/cc_chat.lua:80
       6. __fn - addons/ulib/lua/ulib/shared/commands.lua:951
        7. execute - addons/ulib/lua/ulib/shared/commands.lua:1331
         8. unknown - addons/ulib/lua/ulib/shared/commands.lua:1359
          9. unknown - lua/includes/modules/concommand.lua:54
```

Tested with latest versions of both ULIB/ULX and ULXCC via github

_probably not important, but the server OS is windows on the 64-bit branch of srcds_

**Comment by thebigyap** [comment]
Apologies for the gap in reply, I was only notified 30 minutes ago via GitHub notifications that this was an issue. Consider this fixed in the newest update, which you can download now, as I've just updated the repository. This should have been fixed a while ago, I once again apologize.
